config/routes.rb
StarfishApp::Application.routes.draw do

  get "categories", to: "categories#index"
  resources :projects
  resources :backs
  #root page
  root 'home#index'
  #Users page
  devise_for :users, controller: 'user/users', path_names: {sing_in: "login", sing_out: "logout"}
  namespace :user do
  resources :projects do
    resources :pledges
  end
    resources :backs do 
      collection do
        get :list 
      end
    end
  end
  resources :projects do
    resources :backs do
      member do
        get :list 
      end
    end
  end
  #resources :backs, controller: 'user/backs
  #get 'users/backs', to: 'user/backs#list' 
  #admin page
  namespace :admin do
    resources :categories, :home 
    resources :projects do 
      member do
        get :approve
      end
      collection do
        get :monney_to_give
        get :monney_to_give_betwen_dates
      end
    end
    resources :backs do
      collection do
        get :revenue
      end
    end
  end

end

app/models/project.rb
class Project < ActiveRecord::Base

  #Database Relations
  belongs_to :user
  belongs_to :category
  has_many :backs
  has_many :pledges
  #Validations
  validates_presence_of :name
  validates_presence_of :city
  validates_presence_of :close_date
  validates_presence_of :description
  validates_presence_of :video_url
  validates_presence_of :amount
  validates_presence_of :user_id
  validates_presence_of :category_id

  validates_numericality_of :amount
  validates_uniqueness_of :name 

  validates_format_of :video_url, :with => %r{\.(mp4|ogg|ogv)}
  mount_uploader :video_url, ProjectVideoUploader

  scope :non_closed, -> { where('close_date > :today', today: Time.now) }
  scope :non_successful, -> { where('money_raised <= amount').closed } 
  scope :successful, -> { where('money_raised >= amount').closed } 
  scope :closed, -> { where('close_date < :today', today: Time.now) }

  def sum_money(amount)
    unless self.money_raised.nil?
      self.money_raised += amount
    else
      self.money_raised + amount
    end
    self.save
  end

  def self.list_project_between(init_date,end_date)
    self.select("name,money_raised").where("close_date >= :init_date AND close_date <= :end_date",
                                           init_date: init_date, end_date: end_date).order('id ASC')
  end

  def approve!
    self.approved = true
    self.save
  end
end

app/controllers/admin/projects_controller.rb
class Admin::ProjectsController < Admin::BaseController
  def index
    @projects = Project.all
    respond_to do |format|
      format.html
      format.json { render json: @projects}
    end
  end
  def approve
    @project = Project.find(params[:id])
    @project.approve!
    redirect_to projects_url
  end

  def destroy
    redirect_to projects_url if @project.destroy
  end

  def monney_to_give
    unless params[:s_date].nil?
      @projects = Project.list_project_between(params[:s_date].to_date,params[:e_date].to_date).successful
      @money = Project.successful.sum('money_raised')
    else
      @projects = Project.all.order('id ASC').successful    ##calculate_backs
      @money = Project.successful.sum('money_raised')
    end
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  
  before_action :set_project, only: [:show]

  def index
    @projects = Project.all

    respond_to do |format|
      format.html
      format.json { render json: @projects}
    end
  end

  def show
    flash[:notice] = ""
    @project = Project.find(params[:id])
    @users = User.joins(:backs).where(backs: {project_id: params[:id]})
    @owner = User.find(@project.user_id)
    project_time_to_close
    date_to_close
    respond_to do |format|
      format.html
    end
  end
  def project_time_to_close
    @project = Project.find(params[:id])
    @time_now = Time.now
    if @time_now >= @project.close_date
      flash[:notice] = "The Project was Closed"
      @close_date = 1
    else
      @close_date = 0
    end
  end

  def date_to_close
    @project  = Project.find(params[:id])
    @date_finish = Date.parse("#{@project.close_date}")
    @date_now = Date.today
    @time_to_finish = (@date_finish - @date_now).to_i
    @time_to_finish = 0 if @time_to_finish <= 0
  end
private

  def set_project
    @project = Project.find(params[:id])
  end

end

app/controllers/user/projects_controller.rb
class User::ProjectsController < User::BaseController
  
  before_action :set_project, only: [:show,:edit,:update,:destroy]

  def index
    @projects = Project.all
    respond_to do |format|
      format.html
      format.json { render json: @projects}
    end
  end

  def show
    @project = Project.find(params[:id])
    @users = User.joins(:backs).where(backs: {project_id: params[:id]})
    @owner = User.find(@project.user_id)
    respond_to do |format|
      format.html
      #format.json { render json: @users}
    end
  end

  def new
    @project = Project.new
  end

  def edit
    @project = Project.find(params[:id])
  end

  def create
    @project = Project.new(project_params)
    respond_to do |format|
      if @project.save and !params[:preview]
        format.html { redirect_to user_project_path(@project), notice: 'Project was successfully created.' } 
      else
        if params[:preview] 
          format.html {render action: "preview"}
        else
          format.html { render action: 'new' }
          format.json { render json: @project.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  def edit_preview 
    render action: 'new'
  end
  def update
    @project = Project.find(params[:id])
    if @project.update(project_params)
      redirect_to @project, notice: "Project was successfully updated."
    else
      render "edit"
    end
  end

  def destroy
    redirect_to projects_url if @project.destroy
  end

private

  def set_project
    @project = Project.find(params[:id])
  end

  def project_params
    params.require(:project).permit( :name, :city, :close_date, :description, :amount, :video_url,:user_id, :category_id, :approved)
  end
end

app/helpers/admin/projects_helper.rb
module Admin::ProjectsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/user/projects_helper.rb
module User::ProjectsHelper
end

app/views/projects/index.html.haml
%section
  %h2 Current projects
  %br
  %table.table.table-striped
    %thead
      %tr
        %th Id
        %th Name
    - @projects.each do |project|
      %tr
        %td #{ project.id }
        %td #{ project.name }
        %td
          = link_to "Show", project
  = link_to "Back", root_path

app/views/projects/show.html.haml
#main-project-container
  %section
    .notice
    = flash[:notice]
    .project-header
      %h2= @project.name
      %p
        by 
        = @owner.email
    .project-container.modal
      .container-head
        .project-video
          -#%iframe{:allowfullscreen => "", :frameborder => "0", :height => "480px", :src => "//www.youtube.com/embed/jvEaOBty6xI", :width => "640"}
          = video_tag @project.video_url, :size => "640x480", :controls => true
        .project-donations
          %h1
            = @users.count
          %h5 Bakers
          %h1
            = @project.money_raised
          %h5 
            Pledged of
          %h1
            $
            = @project.amount
            %h5 to goal
          %h1 
            = @time_to_finish
          %h5 Days to go
          %br  
          %br
          - if user_signed_in?
            - if @owner.id != current_user.id
              - if @close_date == 1
                .btn.btn-large.btn-block.btn-danger
                  THIS PROJECT IS CLOSED
              - else
                = link_to "Back this project", new_project_back_path(:project_id => @project.id), class: "btn btn-large btn-block btn-primary"
            - else
              .btn.btn-large.btn-block.btn-danger
                You can NOT back your own project
          - else
            .btn.btn-large.btn-block.btn-danger
              You can NOT back if you aren't logged in

          %h2 Backers
          - @users.each do |user|
            %tr
              %td #{user.email}
              %br
          %br
          %br
      .project-description
        %h3 Project Description
        %p
          Ciudad:
          = @project.city
          Close date
          = @project.close_date
        = @project.description