config/routes.rb
StarfishApp::Application.routes.draw do

  get "categories", to: "categories#index"
  resources :projects
  resources :backs
  #root page
  root 'home#index'
  #Users page
  devise_for :users, controller: 'user/users', path_names: {sing_in: "login", sing_out: "logout"}
  namespace :user do
  resources :projects do
    resources :pledges
  end
    resources :backs do 
      collection do
        get :list 
      end
    end
  end
  resources :projects do
    resources :backs do
      member do
        get :list 
      end
    end
  end
  #resources :backs, controller: 'user/backs
  #get 'users/backs', to: 'user/backs#list' 
  #admin page
  namespace :admin do
    resources :categories, :home 
    resources :projects do 
      member do
        get :approve
      end
      collection do
        get :monney_to_give
        get :monney_to_give_betwen_dates
      end
    end
    resources :backs do
      collection do
        get :revenue
      end
    end
  end

end

app/models/back.rb
class Back < ActiveRecord::Base
  belongs_to :project
  belongs_to :user
end

app/models/category.rb
class Category < ActiveRecord::Base

  #Database Relations
  has_many :projects

  #Validations
  validates_presence_of   :name
  validates_uniqueness_of :name

end

app/models/pledge.rb
class Pledge < ActiveRecord::Base
  belongs_to :project
end

app/models/project.rb
class Project < ActiveRecord::Base

  #Database Relations
  belongs_to :user
  belongs_to :category
  has_many :backs
  has_many :pledges
  #Validations
  validates_presence_of :name
  validates_presence_of :city
  validates_presence_of :close_date
  validates_presence_of :description
  validates_presence_of :video_url
  validates_presence_of :amount
  validates_presence_of :user_id
  validates_presence_of :category_id

  validates_numericality_of :amount
  validates_uniqueness_of :name 

  validates_format_of :video_url, :with => %r{\.(mp4|ogg|ogv)}
  mount_uploader :video_url, ProjectVideoUploader

  scope :non_closed, -> { where('close_date > :today', today: Time.now) }
  scope :non_successful, -> { where('money_raised <= amount').closed } 
  scope :successful, -> { where('money_raised >= amount').closed } 
  scope :closed, -> { where('close_date < :today', today: Time.now) }

  def sum_money(amount)
    unless self.money_raised.nil?
      self.money_raised += amount
    else
      self.money_raised + amount
    end
    self.save
  end

  def self.list_project_between(init_date,end_date)
    self.select("name,money_raised").where("close_date >= :init_date AND close_date <= :end_date",
                                           init_date: init_date, end_date: end_date).order('id ASC')
  end

  def approve!
    self.approved = true
    self.save
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :projects
  has_many :backs
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

end

app/controllers/admin/home_controller.rb
class Admin::HomeController < Admin::BaseController
  def index
    
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def index
    unless current_user == nil
      redirect_to admin_home_index_path if current_user.admin
    end
  end
end

app/controllers/backs_controller.rb
class BacksController < ApplicationController
  def index
  end
  def new
    @back = Back.new
    @pledge = Pledge.where(:project_id => params[:project_id]).order("min ASC")
  end

  def create
    @back = current_user.backs.new(back_params)
    @back.project_id = params[:project_id]
    if @back.save
      Project.find(params[:project_id]).sum_money(@back.amount)
      redirect_to :back
    else
      render :back
    end
  end

  private
  def back_params
    params.require(:back).permit(:amount,:pledge_id)
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @category = Category.all
    respond_to do |format|
      #format.html
      format.json { render json: @category}
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  
  before_action :set_project, only: [:show]

  def index
    @projects = Project.all

    respond_to do |format|
      format.html
      format.json { render json: @projects}
    end
  end

  def show
    flash[:notice] = ""
    @project = Project.find(params[:id])
    @users = User.joins(:backs).where(backs: {project_id: params[:id]})
    @owner = User.find(@project.user_id)
    project_time_to_close
    date_to_close
    respond_to do |format|
      format.html
    end
  end
  def project_time_to_close
    @project = Project.find(params[:id])
    @time_now = Time.now
    if @time_now >= @project.close_date
      flash[:notice] = "The Project was Closed"
      @close_date = 1
    else
      @close_date = 0
    end
  end

  def date_to_close
    @project  = Project.find(params[:id])
    @date_finish = Date.parse("#{@project.close_date}")
    @date_now = Date.today
    @time_to_finish = (@date_finish - @date_now).to_i
    @time_to_finish = 0 if @time_to_finish <= 0
  end
private

  def set_project
    @project = Project.find(params[:id])
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_filter :authenticate_user!, except:[:index]

  def index
    unless current_user == nil
      redirect_to administrators_path if current_user.admin
    end
  end

  def show
    @user = User.find(params[:id])
  end

end

app/helpers/admin/backs_helper.rb
module Admin::BacksHelper
end

app/helpers/admin/base_helper.rb
module Admin::BaseHelper
end

app/helpers/admin/home_helper.rb
module Admin::HomeHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/baks_helper.rb
module BaksHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/user/backs_helper.rb
module User::BacksHelper
  def optain_name(id)
    project_name = Project.select("name").where(id: id).send(params[:scope])
    unless project_name[0].nil?
      return project_name[0].name
    end
    nil
  end

  def load_li_active
    list = ["","",""]
    if params[:scope] == "non_closed"
      list[0] = "active"
    elsif params[:scope] == "closed"
      list[1] = "active"
    else
      list[2] = "active"
    end
    list
  end
end

app/helpers/user/base_helper.rb
module User::BaseHelper
end

app/helpers/user/projects_helper.rb
module User::ProjectsHelper
end

app/helpers/user/users_helper.rb
module User::UsersHelper
end

app/views/admin/home/index.html.haml
%section
  %h1 Administrator
  %br
  = link_to "View current projects", admin_projects_path 
  %br
  = link_to "View project categories", admin_categories_path 
  %br
  = link_to "Check how much monney is commited to be given", monney_to_give_admin_projects_path
  %br
  %br
 

app/views/home/index.html.haml
.main-board
  %section.board
    %h2 Our great project!
    %h4 This is a great stuff suport us
    %button.btn.btn-small.btn-info{:type => "button"} Learn More 
%section
  .main-project
    .main-project-header
      .main-project-header-cell-left
        %h4 Staff picks: Tecnology
      .main-project-header-cell-right
        See all 
        %strong 340 
        Tecnology projects
    .main-project-video
      %iframe{:allowfullscreen => "", :frameborder => "0", :width => "340", :height => "250", :src => "//www.youtube.com/embed/AkQvzvzf1sc"}
    //.divider.section.transparent
    .main-project-content
      %p Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim.
      %br
      .progress
        .bar{:style => "width: 60%;"}
      %br
      .span1
        %strong 60%
        %br
        %small.muted funded
      .span1
        %strong $40,342
        %br
        %small.muted pledged
      .span1
        %strong 21
        %br
        %small.muted Days left
  .categories
    %p Art
    %p Comics
    %p Dance
    %p Design
    %p Fashion
    %p Film & Video
    %p Food
    %p Games
    %p Music
    %p Photography
    %p Publishing
    %p.text-info Tecnology
    %p Theater
%section.projects-main
  %section.projects-header
    .ps-header-left
      .p_icon.popular
        %h4 Popular
    .ps-header-right
      See all
  #projectsMain.carousel.slide{"ng-controller" => "projectsController", "ng-init" => "showProjects()"}
    %ol.carousel-indicators
      %li.active{"data-slide-to" => "0", "data-target" => "#projectsMain"}
      %li{"data-slide-to" => "1", "data-target" => "#projectsMain"}
    .carousel-inner{ :style => 'height: 350px' }
      .active.item
        %section.projects-block
          %div.row-fluid
            %ul.thumbnails
              %li.span3
                .thumbnail
                  .img-thumbnail.project3
                  .caption
                    %h3 Personal dog
                    %p Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore.
                    %a.btn.btn-primary Personal Dog
              %li.span3
                .thumbnail
                  .img-thumbnail.project1
                  .caption
                    %h3 Robotic People
                    %p Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore.
                    %a.btn.btn-primary Robotic People
              %li.span3
                .thumbnail
                  .img-thumbnail.project2
                  .caption
                    %h3 Born to help
                    %p Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore.
                    %a.btn.btn-primary Born to help
              %li.span3
                .thumbnail
                  .img-thumbnail.project3
                  .caption
                    %h3 Just do it
                    %p Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore.
                    %a.btn.btn-primary Just do it
      .item 
        %section.projects-block
          %div.row-fluid
            %ul.thumbnails
              %li.span3{"ng-repeat" => "project in projects"}
                .thumbnail
                  .img-thumbnail.project2
                  .caption
                    %h3 {{ project.name }} 
                    %p {{ project.description }}
                    %a.btn.btn-primary{:href => "projects/{{project.id}}"} {{ project.name}} 
    %a.carousel-control.left{"data-slide" => "prev", :href => "#projectsMain"} ‹
    %a.carousel-control.right{"data-slide" => "next", :href => "#projectsMain"} ›
.main-board.facebook
  %section.board.facebook
    %h2 Discover great projects with your friends
    %br
    %button.btn.btn-large.btn-primary{:type => "button"} 
      %i.icon-thumbs-up.iconsw 
      log in with facebook
%section.curated-pages
  %section.projects-header
    .ps-header-left
      .p_icon.curated
        %h4 Curated Pages
    .ps-header-right
      See all
  #pagesMain.carousel.slide
    %ol.carousel-indicators
      %li.active{"data-slide-to" => "0", "data-target" => "#pagesMain"}
      %li{"data-slide-to" => "1", "data-target" => "#pagesMain"}
    .carousel-inner{ :style => 'height: 200px' }
      .active.item
        %section.projects-block.pages
          %div.row-fluid
            %ul.thumbnails
              %li.span2
                .thumbnail
                  .img-page.project1
              %li.span2
                .thumbnail
                  .img-page.project2
              %li.span2
                .thumbnail
                  .img-page.project3
              %li.span2
                .thumbnail
                  .img-page.project4
              %li.span2
                .thumbnail
                  .img-page.project5
              %li.span2
                .thumbnail
                  .img-page.project6
      .item 
        %section.projects-block.pages
          %div.row-fluid
            %ul.thumbnails
              %li.span2
                .thumbnail
                  .img-page.project7
              %li.span2
                .thumbnail
                  .img-page.project8
              %li.span2
                .thumbnail
                  .img-page.project9
              %li.span2
                .thumbnail
                  .img-page.project10
              %li.span2
                .thumbnail
                  .img-page.project11
              %li.span2
                .thumbnail
                  .img-page.project12
      .item 
        %section.projects-block.pages
          %div.row-fluid
            %ul.thumbnails
              %li.span2
                .thumbnail
                  .img-page.project13
    %a.carousel-control.left{"data-slide" => "prev", :href => "#pagesMain"} ‹
    %a.carousel-control.right{"data-slide" => "next", :href => "#pagesMain"} ›
.main-board.make
  %section.board.make
    %h2{:style => 'color: rgb(255,255,255)'} 
      Where projects come from
    %p{:style => 'color: rgb(0,0,0)'}  
      Each and every Starfish project is the independent creation of someone like you.
      %br
      Want to know more about how projects happen, or start your own?
      %a{:style => 'color: rgb(255,255,255)'} Learn More