config/routes.rb
StarfishApp::Application.routes.draw do

  get "categories", to: "categories#index"
  resources :projects
  resources :backs
  #root page
  root 'home#index'
  #Users page
  devise_for :users, controller: 'user/users', path_names: {sing_in: "login", sing_out: "logout"}
  namespace :user do
  resources :projects do
    resources :pledges
  end
    resources :backs do 
      collection do
        get :list 
      end
    end
  end
  resources :projects do
    resources :backs do
      member do
        get :list 
      end
    end
  end
  #resources :backs, controller: 'user/backs
  #get 'users/backs', to: 'user/backs#list' 
  #admin page
  namespace :admin do
    resources :categories, :home 
    resources :projects do 
      member do
        get :approve
      end
      collection do
        get :monney_to_give
        get :monney_to_give_betwen_dates
      end
    end
    resources :backs do
      collection do
        get :revenue
      end
    end
  end

end

app/models/back.rb
class Back < ActiveRecord::Base
  belongs_to :project
  belongs_to :user
end

app/models/category.rb
class Category < ActiveRecord::Base

  #Database Relations
  has_many :projects

  #Validations
  validates_presence_of   :name
  validates_uniqueness_of :name

end

app/models/pledge.rb
class Pledge < ActiveRecord::Base
  belongs_to :project
end

app/models/project.rb
class Project < ActiveRecord::Base

  #Database Relations
  belongs_to :user
  belongs_to :category
  has_many :backs
  has_many :pledges
  #Validations
  validates_presence_of :name
  validates_presence_of :city
  validates_presence_of :close_date
  validates_presence_of :description
  validates_presence_of :video_url
  validates_presence_of :amount
  validates_presence_of :user_id
  validates_presence_of :category_id

  validates_numericality_of :amount
  validates_uniqueness_of :name 

  validates_format_of :video_url, :with => %r{\.(mp4|ogg|ogv)}
  mount_uploader :video_url, ProjectVideoUploader

  scope :non_closed, -> { where('close_date > :today', today: Time.now) }
  scope :non_successful, -> { where('money_raised <= amount').closed } 
  scope :successful, -> { where('money_raised >= amount').closed } 
  scope :closed, -> { where('close_date < :today', today: Time.now) }

  def sum_money(amount)
    unless self.money_raised.nil?
      self.money_raised += amount
    else
      self.money_raised + amount
    end
    self.save
  end

  def self.list_project_between(init_date,end_date)
    self.select("name,money_raised").where("close_date >= :init_date AND close_date <= :end_date",
                                           init_date: init_date, end_date: end_date).order('id ASC')
  end

  def approve!
    self.approved = true
    self.save
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :projects
  has_many :backs
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def index
    unless current_user == nil
      redirect_to admin_home_index_path if current_user.admin
    end
  end
end

app/controllers/backs_controller.rb
class BacksController < ApplicationController
  def index
  end
  def new
    @back = Back.new
    @pledge = Pledge.where(:project_id => params[:project_id]).order("min ASC")
  end

  def create
    @back = current_user.backs.new(back_params)
    @back.project_id = params[:project_id]
    if @back.save
      Project.find(params[:project_id]).sum_money(@back.amount)
      redirect_to :back
    else
      render :back
    end
  end

  private
  def back_params
    params.require(:back).permit(:amount,:pledge_id)
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @category = Category.all
    respond_to do |format|
      #format.html
      format.json { render json: @category}
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  
  before_action :set_project, only: [:show]

  def index
    @projects = Project.all

    respond_to do |format|
      format.html
      format.json { render json: @projects}
    end
  end

  def show
    flash[:notice] = ""
    @project = Project.find(params[:id])
    @users = User.joins(:backs).where(backs: {project_id: params[:id]})
    @owner = User.find(@project.user_id)
    project_time_to_close
    date_to_close
    respond_to do |format|
      format.html
    end
  end
  def project_time_to_close
    @project = Project.find(params[:id])
    @time_now = Time.now
    if @time_now >= @project.close_date
      flash[:notice] = "The Project was Closed"
      @close_date = 1
    else
      @close_date = 0
    end
  end

  def date_to_close
    @project  = Project.find(params[:id])
    @date_finish = Date.parse("#{@project.close_date}")
    @date_now = Date.today
    @time_to_finish = (@date_finish - @date_now).to_i
    @time_to_finish = 0 if @time_to_finish <= 0
  end
private

  def set_project
    @project = Project.find(params[:id])
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_filter :authenticate_user!, except:[:index]

  def index
    unless current_user == nil
      redirect_to administrators_path if current_user.admin
    end
  end

  def show
    @user = User.find(params[:id])
  end

end

app/helpers/admin/base_helper.rb
module Admin::BaseHelper
end

app/helpers/admin/home_helper.rb
module Admin::HomeHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/baks_helper.rb
module BaksHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/user/backs_helper.rb
module User::BacksHelper
  def optain_name(id)
    project_name = Project.select("name").where(id: id).send(params[:scope])
    unless project_name[0].nil?
      return project_name[0].name
    end
    nil
  end

  def load_li_active
    list = ["","",""]
    if params[:scope] == "non_closed"
      list[0] = "active"
    elsif params[:scope] == "closed"
      list[1] = "active"
    else
      list[2] = "active"
    end
    list
  end
end

app/helpers/user/base_helper.rb
module User::BaseHelper
end

app/views/layouts/_footer.html.haml
%footer
  .main-board.footer
    %section.footer
      .span2
        %h5 Discover
        %br
        Art
        %br
        Comics
        %br
        Dance
        %br
        Design
        %br
        Fashion
        %br
        Film & Video
        %br
        Food
      .span2
        %br
        %br
        Games
        %br
        Music
        %br
        Photography
        %br
        Publishing
        %br
        Technology
        %br
        Theater
      .span2
        %br
        %br
        Staff Picks
        %br
        Popular
        %br
        Recently Launched
        %br
        Small Projects
        %br
        Most Funded
        %br
        Curated Pages
      .span2
        %h5 Create
        Start a project
        %br
        Starfish Academy
        %br
        Creator Questions
        %br
        Project Guidelines
      .span2
        %h5 About
        What is Starfish?
        %br
        Project Guidelines
        %br
        Meet our team
        %br
        Work at Starfish
        %br
        Press
        %br
        Stats
        %br
        Best of Starfish 2012
        %br
        Project Guidelines
      .span2
        %h5 Stay in touch
        Blog
        %br
        Newsletter
        %br
        Twitter
        %br
        Tumblr
        %br
        Facebook
    %section.footer.middle
      %h4 
        "Here goes quotes about the site"
        %button.btn 
          %i.icon-eye-open.iconsb
          @Folow in Twitter
        %button.btn.btn-info 
          %i.icon-thumbs-up.iconsw
          Like in facebook
    %section.footer.middle.down
      About, privacy, Copyright, Terms of use, etc.
      

app/views/layouts/_menu.html.haml
%header.sf-main
  .header-content
    = link_to "Home", root_path
    .divider
    = link_to "About Starfish"
    .divider
    = link_to "Discover great projects", projects_path
    .divider
    = link_to "Start your project", new_user_project_path 
    .divider
    %input.search-query{:type => 'text', :placeholder => 'Search'}
    .divider
    - if user_signed_in?
      =current_user.email
      |
      = link_to "Sign out", destroy_user_session_path, :method => 'delete'
    - else
      = link_to "New Account", new_user_registration_path
      |
      = link_to "Log in", new_user_session_path

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>StarfishApp</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div id="user_nav">
        <% if user_signed_in? %>
          Logged in as <strong><%= current_user.email %></strong>.
          <%= link_to 'Edit profile', edit_user_registration_path %> |
          <%= link_to "Logout", destroy_user_session_path, method: :delete %> |
          <%= link_to "My Profile", user_path(@user) %>
        <% else %>
          <%= link_to "Sign up", new_user_registration_path %> |
          <%= link_to "Login", new_user_session_path %>
        <% end %>
      </div>

      <% flash.each do |name, msg| %>
        <%= content_tag :div, msg, id: "flash_#{name}" %>
      <% end %>
<%= yield %>

</body>
</html>

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title StarfishApp
    = stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = csrf_meta_tags
  %body
    #main-container
      = render 'layouts/menu'
      = yield
      = render 'layouts/footer'